describe('VolumeStructures service test', function () {
    var volumeStructures, httpBackend;

    beforeEach(function () {
        module('app.volumeModule');
    });

    beforeEach(inject(function (_volumeStructures_, $httpBackend) {
        volumeStructures = _volumeStructures_;
        httpBackend = $httpBackend;
    }));

    it('', function () {

        // Prepare fake http response for testing.
        httpBackend.whenGET('http://webdev.connectomes.utah.edu/RC1Test/OData/StructureTypes').respond({
            "@odata.context": "http://webdev.connectomes.utah.edu/RC1Test/OData/$metadata#StructureTypes",
            "value": [
                {
                    "ID": 1,
                    "ParentID": null,
                    "Name": "Cell                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -16776961,
                    "Version": "AAAAAAB4+gs=",
                    "Code": "C               ",
                    "HotKey": "\u0000",
                    "Username": "155.101.240.111 ",
                    "LastModified": "2010-04-07T20:29:54.227-06:00",
                    "Created": "2010-04-07T17:25:12.547-06:00"
                }, {
                    "ID": 28,
                    "ParentID": 1,
                    "Name": "Gap Junction                                                                                                                    ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -256,
                    "Version": "AAAAAAWZhe0=",
                    "Code": "G               ",
                    "HotKey": "0",
                    "Username": "u0284607        ",
                    "LastModified": "2014-10-27T22:27:24.877-06:00",
                    "Created": "2010-04-07T17:25:12.547-06:00"
                }, {
                    "ID": 31,
                    "ParentID": null,
                    "Name": "Bipolar                                                                                                                         ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -16711936,
                    "Version": "AAAAAAB4+g8=",
                    "Code": "B               ",
                    "HotKey": "0",
                    "Username": "                ",
                    "LastModified": "2010-09-07T21:10:58.593-06:00",
                    "Created": "2010-04-07T17:25:12.547-06:00"
                }, {
                    "ID": 34,
                    "ParentID": 1,
                    "Name": "Conventional                                                                                                                    ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -65536,
                    "Version": "AAAAAAHv8kc=",
                    "Code": "CS              ",
                    "HotKey": "0",
                    "Username": "Joshua          ",
                    "LastModified": "2014-03-28T18:18:04.337-06:00",
                    "Created": "2010-04-07T17:25:12.547-06:00"
                }, {
                    "ID": 35,
                    "ParentID": 1,
                    "Name": "Postsynapse                                                                                                                     ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -32768,
                    "Version": "AAAAAACIkuM=",
                    "Code": "PSD             ",
                    "HotKey": "0",
                    "Username": "jhoang          ",
                    "LastModified": "2011-08-10T21:00:23.383-06:00",
                    "Created": "2010-04-07T17:25:12.547-06:00"
                }, {
                    "ID": 73,
                    "ParentID": 1,
                    "Name": "Ribbon Synapse                                                                                                                  ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -8323328,
                    "Version": "AAAAAAX25Tk=",
                    "Code": "R               ",
                    "HotKey": " ",
                    "Username": "nicholasmcc4    ",
                    "LastModified": "2015-02-06T20:08:56.53-07:00",
                    "Created": "2010-04-07T17:25:12.547-06:00"
                }, {
                    "ID": 80,
                    "ParentID": 226,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "Test Structure I can easily delete after features are completed",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -16711936,
                    "Version": "AAAAAACJfcs=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "jhoang          ",
                    "LastModified": "2011-08-16T23:01:24.743-06:00",
                    "Created": "2010-04-07T17:25:12.547-06:00"
                }, {
                    "ID": 81,
                    "ParentID": 1,
                    "Name": "Organized SER                                                                                                                   ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -1,
                    "Version": "AAAAAACxrm0=",
                    "Code": "OSER            ",
                    "HotKey": "\u0000",
                    "Username": "robertmarc      ",
                    "LastModified": "2012-06-21T18:01:53.237-06:00",
                    "Created": "2010-04-07T17:25:12.547-06:00"
                }, {
                    "ID": 85,
                    "ParentID": 1,
                    "Name": "Adherens                                                                                                                        ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -32576,
                    "Version": "AAAAAAX2Qec=",
                    "Code": "A               ",
                    "HotKey": "\u0000",
                    "Username": "u0284607        ",
                    "LastModified": "2015-02-02T23:55:28.36-07:00",
                    "Created": "2010-04-07T17:25:12.547-06:00"
                }, {
                    "ID": 181,
                    "ParentID": 1,
                    "Name": "Cistern Pre                                                                                                                     ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -16744256,
                    "Version": "AAAAAAPj5Tg=",
                    "Code": "CPre            ",
                    "HotKey": "\u0000",
                    "Username": "jamesan         ",
                    "LastModified": "2014-07-16T19:51:03.06-06:00",
                    "Created": "2010-04-07T17:25:12.547-06:00"
                }, {
                    "ID": 182,
                    "ParentID": 1,
                    "Name": "Cistern Post                                                                                                                    ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -8323073,
                    "Version": "AAAAAAX+8AE=",
                    "Code": "CPst            ",
                    "HotKey": "\u0000",
                    "Username": "robertmarc      ",
                    "LastModified": "2015-03-20T22:18:08.453-06:00",
                    "Created": "2010-04-07T17:25:12.547-06:00"
                }, {
                    "ID": 183,
                    "ParentID": 1,
                    "Name": "Cilium                                                                                                                          ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -12582848,
                    "Version": "AAAAAAC1Uuk=",
                    "Code": "CIL             ",
                    "HotKey": "\u0000",
                    "Username": "robertmarc      ",
                    "LastModified": "2012-10-18T21:15:08.14-06:00",
                    "Created": "2010-04-07T17:25:12.547-06:00"
                }, {
                    "ID": 189,
                    "ParentID": 1,
                    "Name": "BC Conventional Synapse                                                                                                         ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -8355840,
                    "Version": "AAAAAAX1bGU=",
                    "Code": "BCS             ",
                    "HotKey": "\u0000",
                    "Username": "jamesan         ",
                    "LastModified": "2015-01-26T21:53:37.13-07:00",
                    "Created": "2010-04-07T17:25:12.547-06:00"
                }, {
                    "ID": 219,
                    "ParentID": 1,
                    "Name": "Multicistern                                                                                                                    ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -8372160,
                    "Version": "AAAAAADCK/4=",
                    "Code": "MCIS            ",
                    "HotKey": "\u0000",
                    "Username": "CLSigulinsky    ",
                    "LastModified": "2013-04-08T22:39:26.61-06:00",
                    "Created": "2010-06-03T18:10:25.757-06:00"
                }, {
                    "ID": 220,
                    "ParentID": 1,
                    "Name": "Endocytosis                                                                                                                     ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -32640,
                    "Version": "AAAAAAYUKXE=",
                    "Code": "Endo            ",
                    "HotKey": "\u0000",
                    "Username": "CLSigulinsky    ",
                    "LastModified": "2015-07-13T17:40:23.553-06:00",
                    "Created": "2010-06-14T17:55:14.35-06:00"
                }, {
                    "ID": 224,
                    "ParentID": null,
                    "Name": "INL-IPL Boundary                                                                                                                ",
                    "Notes": "Boundary between the Inner Nuclear Layer and the Inner Plexiform Layer",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -32768,
                    "Version": "AAAAAADF8/c=",
                    "Code": "INL-IPL         ",
                    "HotKey": "\u0000",
                    "Username": "jamesan         ",
                    "LastModified": "2013-07-23T22:53:02.563-06:00",
                    "Created": "2010-11-03T23:43:52.177-06:00"
                }, {
                    "ID": 225,
                    "ParentID": 1,
                    "Name": "multivesicular body                                                                                                             ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -128,
                    "Version": "AAAAAAB5Sb8=",
                    "Code": "MVB             ",
                    "HotKey": "\u0000",
                    "Username": "robertmarc      ",
                    "LastModified": "2010-12-13T17:04:16.657-07:00",
                    "Created": "2010-12-13T17:04:16.657-07:00"
                }, {
                    "ID": 226,
                    "ParentID": 1,
                    "Name": "Ribosome patch                                                                                                                  ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAB5vtU=",
                    "Code": "RIBO            ",
                    "HotKey": "\u0000",
                    "Username": "robertmarc      ",
                    "LastModified": "2010-12-16T16:24:18.967-07:00",
                    "Created": "2010-12-13T17:04:16.693-07:00"
                }, {
                    "ID": 227,
                    "ParentID": 230,
                    "Name": "Ribbon cluster                                                                                                                  ",
                    "Notes": "Transport",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -8372224,
                    "Version": "AAAAAADCK/w=",
                    "Code": "RibCl           ",
                    "HotKey": "\u0000",
                    "Username": "CLSigulinsky    ",
                    "LastModified": "2013-04-08T22:39:14.72-06:00",
                    "Created": "2010-12-29T17:56:37.06-07:00"
                }, {
                    "ID": 229,
                    "ParentID": 1,
                    "Name": "Touch                                                                                                                           ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -8323073,
                    "Version": "AAAAAADHTVs=",
                    "Code": "Y               ",
                    "HotKey": "\u0000",
                    "Username": "robertmarc      ",
                    "LastModified": "2013-09-18T21:09:52.99-06:00",
                    "Created": "2011-03-15T17:41:56.527-06:00"
                }, {
                    "ID": 230,
                    "ParentID": 73,
                    "Name": "Loop                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -128,
                    "Version": "AAAAAADGMWw=",
                    "Code": "L               ",
                    "HotKey": "\u0000",
                    "Username": "NoahNelson      ",
                    "LastModified": "2013-07-30T19:50:31.94-06:00",
                    "Created": "2011-11-19T00:42:28.117-07:00"
                }, {
                    "ID": 232,
                    "ParentID": 1,
                    "Name": "Polysomes                                                                                                                       ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -3477672,
                    "Version": "AAAAAAC/pzA=",
                    "Code": "POLY            ",
                    "HotKey": "\u0000",
                    "Username": "robertmarc      ",
                    "LastModified": "2013-03-13T22:33:11.697-06:00",
                    "Created": "2013-03-13T22:33:11.697-06:00"
                }, {
                    "ID": 233,
                    "ParentID": null,
                    "Name": "Depth                                                                                                                           ",
                    "Notes": "Marker used to measure depth.  Place the first marker at one point of interest.  Place second at second point of interest.  Display in VikingPlot",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -8355712,
                    "Version": "AAAAAADFzp8=",
                    "Code": "D               ",
                    "HotKey": "\u0000",
                    "Username": "jamesan         ",
                    "LastModified": "2013-07-23T21:16:42.843-06:00",
                    "Created": "2013-07-23T20:49:53.443-06:00"
                }, {
                    "ID": 234,
                    "ParentID": null,
                    "Name": "Marker                                                                                                                          ",
                    "Notes": "Non-biological locations",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -8355712,
                    "Version": "AAAAAADFznc=",
                    "Code": "M               ",
                    "HotKey": "\u0000",
                    "Username": "jamesan         ",
                    "LastModified": "2013-07-23T20:50:24.567-06:00",
                    "Created": "2013-07-23T20:50:24.567-06:00"
                }, {
                    "ID": 235,
                    "ParentID": null,
                    "Name": "IPL-GCL Boundary                                                                                                                ",
                    "Notes": "Marks transition from Inner Plexiform Layer to Ganglion Cell Layer",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -8323328,
                    "Version": "AAAAAADF4N8=",
                    "Code": "IPL-GCL         ",
                    "HotKey": "\u0000",
                    "Username": "jamesan         ",
                    "LastModified": "2013-07-23T22:27:03.02-06:00",
                    "Created": "2013-07-23T20:52:19.503-06:00"
                }, {
                    "ID": 236,
                    "ParentID": 1,
                    "Name": "Plaque                                                                                                                          ",
                    "Notes": "Calcium hot spot",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -16744384,
                    "Version": "AAAAAADGdws=",
                    "Code": "Q               ",
                    "HotKey": "\u0000",
                    "Username": "robertmarc      ",
                    "LastModified": "2013-08-28T17:18:06.33-06:00",
                    "Created": "2013-08-28T17:16:27.197-06:00"
                }, {
                    "ID": 237,
                    "ParentID": 1,
                    "Name": "axon                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -8388353,
                    "Version": "AAAAAADHW5k=",
                    "Code": "X               ",
                    "HotKey": "\u0000",
                    "Username": "robertmarc      ",
                    "LastModified": "2013-09-18T22:24:12.177-06:00",
                    "Created": "2013-09-18T22:24:12.177-06:00"
                }, {
                    "ID": 240,
                    "ParentID": 1,
                    "Name": "Plaque-like Pre                                                                                                                 ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -8355648,
                    "Version": "AAAAAAPj5So=",
                    "Code": "PlPre           ",
                    "HotKey": "\u0000",
                    "Username": "jamesan         ",
                    "LastModified": "2014-07-16T19:02:04.35-06:00",
                    "Created": "2014-07-16T18:39:13.933-06:00"
                }, {
                    "ID": 241,
                    "ParentID": 1,
                    "Name": "Plaque-like Post                                                                                                                ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -8388353,
                    "Version": "AAAAAAPj5Sw=",
                    "Code": "PlPst           ",
                    "HotKey": "\u0000",
                    "Username": "jamesan         ",
                    "LastModified": "2014-07-16T19:02:24.277-06:00",
                    "Created": "2014-07-16T18:58:30.773-06:00"
                }, {
                    "ID": 243,
                    "ParentID": 1,
                    "Name": "Neuroglial adherens                                                                                                             ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -12550016,
                    "Version": "AAAAAAVFvzU=",
                    "Code": "NGadh           ",
                    "HotKey": "\u0000",
                    "Username": "nsherbotie      ",
                    "LastModified": "2014-10-14T18:18:17.453-06:00",
                    "Created": "2014-07-16T19:00:50.433-06:00"
                }, {
                    "ID": 244,
                    "ParentID": 1,
                    "Name": "Unknown                                                                                                                         ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -4144960,
                    "Version": "AAAAAAPj5Sc=",
                    "Code": "U               ",
                    "HotKey": "\u0000",
                    "Username": "jamesan         ",
                    "LastModified": "2014-07-16T19:01:39.533-06:00",
                    "Created": "2014-07-16T19:01:39.533-06:00"
                }, {
                    "ID": 245,
                    "ParentID": 1,
                    "Name": "Nucleolus                                                                                                                       ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -128,
                    "Version": "AAAAAAPj5S0=",
                    "Code": "N               ",
                    "HotKey": "\u0000",
                    "Username": "jamesan         ",
                    "LastModified": "2014-07-16T19:04:49.203-06:00",
                    "Created": "2014-07-16T19:04:49.203-06:00"
                }, {
                    "ID": 246,
                    "ParentID": 1,
                    "Name": "Mitochondria                                                                                                                    ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -8388544,
                    "Version": "AAAAAAPj5Tk=",
                    "Code": "Mito            ",
                    "HotKey": "\u0000",
                    "Username": "jamesan         ",
                    "LastModified": "2014-07-16T20:01:02.47-06:00",
                    "Created": "2014-07-16T20:01:02.47-06:00"
                }, {
                    "ID": 247,
                    "ParentID": 1,
                    "Name": "Caveola                                                                                                                         ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -16711808,
                    "Version": "AAAAAAUE6+8=",
                    "Code": "Cav             ",
                    "HotKey": "\u0000",
                    "Username": "robertmarc      ",
                    "LastModified": "2014-10-02T19:36:04.37-06:00",
                    "Created": "2014-10-02T19:36:04.37-06:00"
                }, {
                    "ID": 248,
                    "ParentID": 1,
                    "Name": "Nuclear filament                                                                                                                ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": ";",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -256,
                    "Version": "AAAAAAXyWww=",
                    "Code": "NF              ",
                    "HotKey": "\u0000",
                    "Username": "robertmarc      ",
                    "LastModified": "2015-01-13T21:31:49.213-07:00",
                    "Created": "2015-01-13T21:30:33.29-07:00"
                }, {
                    "ID": 249,
                    "ParentID": 1,
                    "Name": "Golgi Plaque                                                                                                                    ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -65281,
                    "Version": "AAAAAAXy36U=",
                    "Code": "GP              ",
                    "HotKey": "\u0000",
                    "Username": "robertmarc      ",
                    "LastModified": "2015-01-16T01:23:04.743-07:00",
                    "Created": "2015-01-16T01:23:04.743-07:00"
                }, {
                    "ID": 250,
                    "ParentID": 1,
                    "Name": "Golgi Normal                                                                                                                    ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -8372160,
                    "Version": "AAAAAAXy3+o=",
                    "Code": "GN              ",
                    "HotKey": "\u0000",
                    "Username": "robertmarc      ",
                    "LastModified": "2015-01-16T17:24:26.287-07:00",
                    "Created": "2015-01-16T17:24:26.287-07:00"
                }, {
                    "ID": 252,
                    "ParentID": 1,
                    "Name": "Lysosome                                                                                                                        ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": -16744193,
                    "Version": "AAAAAAXy3/Q=",
                    "Code": "Ly              ",
                    "HotKey": "\u0000",
                    "Username": "robertmarc      ",
                    "LastModified": "2015-01-16T17:26:16.833-07:00",
                    "Created": "2015-01-16T17:26:16.833-07:00"
                }, {
                    "ID": 253,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAaka6k=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-21T22:01:38.84-06:00",
                    "Created": "2015-08-21T22:01:38.84-06:00"
                }, {
                    "ID": 254,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAaka6o=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-21T22:08:10.673-06:00",
                    "Created": "2015-08-21T22:08:10.673-06:00"
                }, {
                    "ID": 255,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAaka70=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-21T22:09:07.303-06:00",
                    "Created": "2015-08-21T22:09:07.303-06:00"
                }, {
                    "ID": 256,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAaka9A=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-21T22:16:15.897-06:00",
                    "Created": "2015-08-21T22:16:15.897-06:00"
                }, {
                    "ID": 257,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAaka+M=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-21T22:18:12.733-06:00",
                    "Created": "2015-08-21T22:18:12.733-06:00"
                }, {
                    "ID": 258,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAaka/Y=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-21T22:23:39.36-06:00",
                    "Created": "2015-08-21T22:23:39.36-06:00"
                }, {
                    "ID": 260,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakbDY=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-21T22:40:45.353-06:00",
                    "Created": "2015-08-21T22:40:45.353-06:00"
                }, {
                    "ID": 261,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakbIU=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-21T22:56:41.777-06:00",
                    "Created": "2015-08-21T22:56:41.777-06:00"
                }, {
                    "ID": 262,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakbIk=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-21T22:58:01.537-06:00",
                    "Created": "2015-08-21T22:58:01.537-06:00"
                }, {
                    "ID": 263,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakbIo=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-21T23:02:18.413-06:00",
                    "Created": "2015-08-21T23:02:18.413-06:00"
                }, {
                    "ID": 264,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakbIs=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-21T23:03:11.91-06:00",
                    "Created": "2015-08-21T23:03:11.91-06:00"
                }, {
                    "ID": 265,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakbIw=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-21T23:04:07.297-06:00",
                    "Created": "2015-08-21T23:04:07.297-06:00"
                }, {
                    "ID": 266,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakbI0=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-21T23:05:35.96-06:00",
                    "Created": "2015-08-21T23:05:35.96-06:00"
                }, {
                    "ID": 267,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakbKA=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-21T23:08:06.003-06:00",
                    "Created": "2015-08-21T23:08:06.003-06:00"
                }, {
                    "ID": 268,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakbLM=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-22T04:58:37.16-06:00",
                    "Created": "2015-08-22T04:58:37.16-06:00"
                }, {
                    "ID": 269,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakbLY=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-22T05:02:12.56-06:00",
                    "Created": "2015-08-22T05:02:12.56-06:00"
                }, {
                    "ID": 270,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakbMk=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-22T05:05:44.253-06:00",
                    "Created": "2015-08-22T05:05:44.253-06:00"
                }, {
                    "ID": 271,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakbNw=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-08-22T05:06:46.277-06:00",
                    "Created": "2015-08-22T05:06:46.277-06:00"
                }, {
                    "ID": 276,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakmmw=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-09-04T05:00:14.337-06:00",
                    "Created": "2015-09-04T05:00:14.337-06:00"
                }, {
                    "ID": 277,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakmow=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-09-04T05:00:51.71-06:00",
                    "Created": "2015-09-04T05:00:51.71-06:00"
                }, {
                    "ID": 279,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakmsM=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-09-04T05:04:42.257-06:00",
                    "Created": "2015-09-04T05:04:42.257-06:00"
                }, {
                    "ID": 282,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakn3c=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-09-10T18:02:26.667-06:00",
                    "Created": "2015-09-10T18:02:26.667-06:00"
                }, {
                    "ID": 283,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakn4Q=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-09-10T18:16:44.267-06:00",
                    "Created": "2015-09-10T18:16:44.267-06:00"
                }, {
                    "ID": 284,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakn5E=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-09-10T18:23:17.067-06:00",
                    "Created": "2015-09-10T18:23:17.067-06:00"
                }, {
                    "ID": 285,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakn54=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-09-10T18:25:25.46-06:00",
                    "Created": "2015-09-10T18:25:25.46-06:00"
                }, {
                    "ID": 286,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakn6s=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-09-10T18:30:51.207-06:00",
                    "Created": "2015-09-10T18:30:51.207-06:00"
                }, {
                    "ID": 287,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakn7g=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-09-10T18:44:56.953-06:00",
                    "Created": "2015-09-10T18:44:56.953-06:00"
                }, {
                    "ID": 289,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakn9w=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-09-11T21:39:43.68-06:00",
                    "Created": "2015-09-11T21:39:43.68-06:00"
                }, {
                    "ID": 290,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakn+8=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-09-11T21:42:02.33-06:00",
                    "Created": "2015-09-11T21:42:02.33-06:00"
                }, {
                    "ID": 291,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakoAM=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-09-11T21:44:24.31-06:00",
                    "Created": "2015-09-11T21:44:24.31-06:00"
                }, {
                    "ID": 292,
                    "ParentID": null,
                    "Name": "Test                                                                                                                            ",
                    "Notes": "",
                    "MarkupType": "Point           ",
                    "Tags": "",
                    "StructureTags": "",
                    "Abstract": false,
                    "Color": 0,
                    "Version": "AAAAAAakoBY=",
                    "Code": "T               ",
                    "HotKey": "\u0000",
                    "Username": "localhost       ",
                    "LastModified": "2015-09-11T21:48:24.567-06:00",
                    "Created": "2015-09-11T21:48:24.567-06:00"
                }
            ]
        });

        // Initialize the volumeStructure service -- this will call the fake http request above.
        volumeStructures.activate();

        // Tell the fake http server to complete the request.
        httpBackend.flush();

        // We expect 32 child structures to be returned.
        expect(volumeStructures.getNumChildStructureTypes() == 32).toBeTruthy();
    });
});