(function () {
    'use strict';

    angular
        .module('app.iplChartModule')
        .factory('iplChartData', iplChartData);

    iplChartData.$inject = ['$log', 'volumeCells', 'volumeLayers'];

    function iplChartData($log, volumeCells, volumeLayers) {

        var self = this;

        self.Status = {
            LOADING: 0,
            ERROR: -1,
            OK: 1
        };

        var service = {
            getIplChartData: getIplChartData
        };

        service.Status = self.Status;

        return service;

        /**
         * @name getColumnDefs
         * @param header - generated by getHeaderData
         * @returns Array columns
         */
        function getIplChartData(cellIndexes) {

            var cellIds = [];
            cellIndexes.forEach(function(cellIndex) {
                cellIds.push(volumeCells.getCellAt(cellIndex).id);
            });

            var data = [];
            cellIds.forEach(function(cellId) {

                var locations = volumeCells.getCellLocations(cellId);

                locations.forEach(function(location) {
                    var result = volumeLayers.convertToIPLPercent(location.position);
                    data.push({
                        location: location,
                        result: result
                    });
                });
            });

            return data;

        }
    }
})();

