(function () {
    'use strict';

    angular
        .module('app.iplChartModule')
        .factory('iplChartData', iplChartData);

    iplChartData.$inject = ['$log', 'volumeCells', 'volumeLayers'];

    function iplChartData($log, volumeCells, volumeLayers) {

        var self = this;

        var service = {
            getIplChartData: getIplChartData,
            getIplRange: getIplRange,
            getHistogramMaxItemsInBins: getHistogramMaxItemsInBins,
            getHistogramBins: getHistogramBins
        };

        service.Status = self.Status;

        return service;

        /**
         * @name getColumnDefs
         * @param header - generated by getHeaderData
         * @returns Array columns
         */
        function getIplChartData(cellIndexes) {

            var cellIds = [];
            cellIndexes.forEach(function (cellIndex) {
                cellIds.push(volumeCells.getCellAt(cellIndex).id);
            });


            var data = [];
            cellIds.forEach(function (cellId) {
                var cellData = [];
                var locations = volumeCells.getCellLocations(cellId);

                locations.forEach(function (location) {
                    var result = volumeLayers.convertToIPLPercent(location.position);
                    cellData.push({
                        location: location,
                        result: result
                    });
                });

                data.push(cellData);
            });

            return data;

        }

        function getIplRange(data) {

            // IPL should be in the range (-0.5, 1.0)
            var minIpl = 100.0;
            var maxIpl = -100.0;

            data.forEach(function (results) {
                results.forEach(function (result) {
                    minIpl = Math.min(result.result.percent, minIpl);
                    maxIpl = Math.max(result.result.percent, maxIpl);
                });
            });

            return [minIpl, maxIpl];
        }

        function getHistogramBins(data, numBins, domain, range) {

            var scale = d3.scale.linear()
                .domain(domain)
                .range(range);

            var justValues = data.map(function (d) {
                return d.result.percent;
            });

            return d3.layout.histogram()
                .range(range)
                .bins(scale.ticks(numBins))
                (justValues);
        }

        function getHistogramMaxItemsInBins(data, numBins, domain, range) {

            var maxItemsInBins = 0;

            data.forEach(function (results) {
                var bins = getHistogramBins(results, numBins, domain, range);
                bins.forEach(function (bin) {
                    maxItemsInBins = Math.max(bin.length, maxItemsInBins);
                });
            });

            return maxItemsInBins;
        }

    }
})();

